// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Demo

#include "ui.h"

void TurnOffLED(lv_event_t * e)
{
	digitalWrite(2,0);
}

void TurnOffLED_(lv_event_t * e)
{
	// Your code here
}

void TurnOnLED(lv_event_t * e)
{
	digitalWrite(2,1);
}

void EnterHide(lv_event_t * e)
{
	// Your code here
}
