// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Demo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TurnOffLED(lv_event_t * e);
void TurnOffLED_(lv_event_t * e);
void TurnOnLED(lv_event_t * e);
void EnterHide(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
