// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Demo

#include "ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -208 );
lv_obj_set_y( ui_Label3, -100 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Wi-Fi:");

ui_Keyboard2 = lv_keyboard_create(ui_Screen2);
lv_obj_set_width( ui_Keyboard2, 480);
lv_obj_set_height( ui_Keyboard2, 120);
lv_obj_set_x( ui_Keyboard2, 0 );
lv_obj_set_y( ui_Keyboard2, 96 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_TextArea1 = lv_textarea_create(ui_Screen2);
lv_obj_set_width( ui_TextArea1, 215);
lv_obj_set_height( ui_TextArea1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextArea1, -69 );
lv_obj_set_y( ui_TextArea1, -100 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );



ui_Button5 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_Button5, 80);
lv_obj_set_height( ui_Button5, 30);
lv_obj_set_x( ui_Button5, 160 );
lv_obj_set_y( ui_Button5, -62 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Retrun");

ui_TextArea3 = lv_textarea_create(ui_Screen2);
lv_obj_set_width( ui_TextArea3, 215);
lv_obj_set_height( ui_TextArea3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextArea3, -69 );
lv_obj_set_y( ui_TextArea3, -50 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_password_mode(ui_TextArea3, true);



ui_Label5 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -206 );
lv_obj_set_y( ui_Label5, -50 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Pass:");

lv_keyboard_set_textarea(ui_Keyboard2,ui_TextArea1);
lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);

}
